services:
  - type: web
    name: backend
    env: node
    plan: free
    buildCommand: "npm install && npx prisma generate"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db-equipamentos
          property: connectionString
      - key: JWT_SECRET
        value: "umSegredoForte"

  - type: web
    name: frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist"
